name: Debug surrealist build
on:
  push:
    branches:
      - create-surrealist-debug
jobs:
  aarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          system = aarch64-linux
    - name: Build
      timeout-minutes: 3000
      run: |
        nix-build -j4 --option system aarch64-linux --option sandbox false --extra-platforms aarch64-linux -A surrealist
        nix show-derivation ./result
